name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou a branch onde você quer que o deploy seja acionado

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências
        run: npm install

      - name: Build do projeto
        run: npm run build

      - name: Deploy para gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages    # branch para onde faremos deploy
          folder: out         # pasta gerada pelo next export
